### ISSUE TITLE
API_URL for https://phenotypes.healthdatagateway.org/

### ISSUE THREAD

**Issue by philipdarke** [SwanseaUniversityMedical/ConceptLibraryClient#1]
Is there a practical difference between the default `API_URL` for the package ([https://conceptlibrary.saildatabank.com/](https://conceptlibrary.saildatabank.com/)) and the API for the new HDR UK phenotype library ([https://phenotypes.healthdatagateway.org/](https://phenotypes.healthdatagateway.org/))? Should I create an API client with `connect_to_API(url="https://phenotypes.healthdatagateway.org/")` to point to the HDR library or am I ok to rely on the default public API connection?

On the face of it they seem to return the same code sets but I wanted to double check before relying on the package.

Thanks for your work on this tool.

**Comment by DSThayer** [comment]
Hi, apologies for the delayed response. 

The HDR UK Phenotype Library is built on the Concept Library and running on the same server. Essentially the Phenotype Library is a white label version of the Concept Library application that displays a subset of the content related to the HDR UK project.

So if you want to access the HDR UK content, the two URLs will function identically. The conceptlibrary.saildatabank.com URL  may also hold additional content that is not included in the HDR UK site, but this content is likely to be minimal going forward--we expect to share anything that meets the definition of a phenotype with HDR UK as well. 

I hope this helps. Let me know if you have further questions/feedback.
