### ISSUE TITLE
Concept library timeout

### ISSUE THREAD

**Issue by rouqueto** [SwanseaUniversityMedical/ConceptLibraryClient#4]
Hi,
I have tried to use the concept library API_client in SAIL but it leads to the following error:

![image](https://github.com/SwanseaUniversityMedical/ConceptLibraryClient/assets/137425031/48e14e15-5151-4914-baf5-47f578eb28ae)

can you help?
Thanks,
Olivier

**Comment by ieuans** [comment]
Legacy issue resolved in emails, caused by missing HTTP/S proxy variables after gateway monthly maintenance
