### ISSUE TITLE
Unable to run code to connect script to SAIL concept libray client 

### ISSUE THREAD

**Issue by SeanScully** [SwanseaUniversityMedical/ConceptLibraryClient#8]
Good afternoon, 

I have been attempting to run the Charlsons Comorbidity script within the SAIL gateway, but have been running into an error when I attempt to connect to the Concept Library via "Client = ConceptLibraryClient::connect_to_API(url  = 'conceptlibrary.serp.ac.uk', public=TRUE)" - Instead I now get the error "connect to API is not an exported object from 'namespace:ConceptLibraryClient'" - This script worked fine until the package was updated recently.  

Kind regards,
Sean

**Comment by ieuans** [comment]
Resolved in Slack, issue with external package SAILDBUtils
