### ISSUE TITLE
Connection timed out

### ISSUE THREAD

**Issue by mdelpozobanos** [SwanseaUniversityMedical/ConceptLibraryClient#9]
Hi,

When trying to access the concept library from SAIL (using code that worked on Friday) I now get the error "Connection timed out after 10008 milliseconds".

Thanks,
Marcos

**Comment by JackScanlon** [comment]
HI Marcos,

I've just double checked and the internal site should be live. I'm thinking this might be a proxy issue, can you double check if you have the `http_proxy` and `https_proxy` environment variables set on your user environment variables please?

**Edit:** Also, few other questions if this doesn't work:
1. Could you please also let me know which API endpoint you're using? I'll take a look to see if there are any errors showing up
2. Which Phenotypes are you trying to access, if any?
3. What version of the ConceptLibrary client are you using? and where did you install it from, was it from Github or from the R drive in the Gateway?

**Comment by mdelpozobanos** [comment]
Hi Jack,

That fixed the issue. Many thanks!

Sorry, I hadn't had to set this up inside SAIL before (that I can remember?). It'll be great if the concept library had a function like `set_environment_variables("Win")` to help with this. You can then catch the exception and rise a message recommending/reminding the user to run such function.

Thanks,
Marcos
________________________________

**Comment by JackScanlon** [comment]
> That fixed the issue. Many thanks!  

Glad it's working now!

> Sorry, I hadn't had to set this up inside SAIL before (that I can remember?).  

Not your fault, quite a few people have had this issue recently - it's possible that this is somehow being reset on people's machines by some update/system, we're going to take a look into why it seems so frequent; hopefully shouldn't have to deal with it again!

> It'll be great if the concept library had a function like `set_environment_variables("Win")` to help with this. You can then catch the exception and rise a message recommending/reminding the user to run such function.

This does sound like a good idea considering this issue does cause problems with other internal packages too. Even just a diagnostic hint would be good, I agree - will try to bring it up at the next meeting. Thanks for the suggestion Marcos, it's appreciated!

**Comment by JackScanlon** [comment]
Closing this for now but keeping it referenced to discuss your suggestion r.e. the method of running diagnostics / a set up tool for internal packages. 

Thanks again
